### ISSUE TITLE
PROGRESS BAR WONT SHOW

### ISSUE THREAD

**Issue by mrshiljo** [BeneSim/BeneOverlay#34] opened 2022-02-16 10:47 UTC
Hi!
Awesome software. Now, everything worked on previous pc, i reinstalled all on new one, new xplane installation, new xpuipc, and all works except progress bar wont show. It shows normally destination arrival, what time and mileage, bbut not the bar otself. Freshj installation also from here

**Comment by MichaelPortelas** [comment] 2022-02-20 10:03
hello, I have the same problem everything works and the progress bar is stopping by itself, I did not reinstall anything and the configuration did not change. the progress bar is stopping by itself

Best regard

**Comment by BeneSim** [comment] 2022-02-22 21:36
Duplicate of #35

**Closed as completed by BeneSim** 2022-02-22 21:36 UTC
Labels: bug, duplicate
